### ISSUE TITLE
Layout system

### ISSUE THREAD

**Issue by constantincuy** [constantincuy/go-gui#2]
# Idea
New interface LayoutOptions implemented by different layouting variants.

### BlockLayout (Default) 
Children can be placed anywhere no automatic calculations on children.

### FlexLayout
Flex layout recalculates its children width based on the settings. Similar to the browser version.

#### Options:
**justify-content**: 'flex-start' | 'center' | 'flex-end'
**align-items**: 'flex-start' | 'center' | 'flex-end'

### GridLayout
Children width and height is recalculated based on columns (width) and largest child per row (height)

#### Options:
**column-count**: number of columns for the grid
**gap**: gap in px between elements

## Theming:
Layouting could be integrated into theming with the proposed solution it reuses valid css syntax but handles it slightly different in some cases.

```css
/* BlockLayout  */
rect {
  display: 'block';
}

/* FlexLayout */
rect {
  display: 'flex';
  align-items: 'center';
  justify-content: 'center';
}

/* GridLayout*/
rect {
  display: 'grid';
  gap: 4px;
  column-count: 5;
}
```
